为了保证无论是否出错都能正确地关闭文件，我们可以使用 try ... finally 来实现：
try:
    f = open('/path/to/file', 'r')
    print f.read()
finally:
    if f:
        f.close()
但是每次都这么写实在太繁琐，所以，Python 引入了 with 语句来自动帮我们调用 close() 方法：
with open('/path/to/file', 'r') as f:
    print f.read()